"C:\ACCA\.Common\ACCA_BIMPlatforms\.InstallInfo\ACCA_BIMPlatforms Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\ACCABrowser_32\.InstallInfo\ACCA_ChrBrowser Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\ACCABrowser_64\.InstallInfo\ACCA_ChrBrowser Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\ACCAPreviewHandler\.InstallInfo\ACCAPreviewHandler Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\dotnetfx_4_7\.InstallInfo\dotnetfx Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\DrawingsX_21_11_x64\.InstallInfo\TeighaX Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\Fonts\.InstallInfo\Fonts Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\PriMus-DCF\x32\.InstallInfo\PriMus-DCF Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\PriMus-DCF\x64\.InstallInfo\PriMus-DCF Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\SignTool\.InstallInfo\SignTool Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\Solarius-PV\.InstallInfo\Solarius-PV Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\TeighaX\.InstallInfo\TeighaX Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\TeighaX_3_4\.InstallInfo\TeighaX_3_4 Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\TerMus-BRIDGE\.InstallInfo\TerMus-BRIDGE Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\TerMus-PLUS\.InstallInfo\TerMus-PLUS Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\vcredist_2005\.InstallInfo\vcredist Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\vcredist_2008\.InstallInfo\vcredist Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\vcredist_2010\.InstallInfo\vcredist Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\vcredist_2013\.InstallInfo\vcredist Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\vcredist_2015_2019\.InstallInfo\vcredist Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\vcredist_x86_2008\.InstallInfo\vcredist Installer.exe" -UNISTALL -SILENTMODE
"C:\ACCA\.Common\Windows_Installer_3_1\.InstallInfo\Windows_Installer_3_1 Installer.exe" -UNISTALL -SILENTMODE